name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 1
        path: 'nixos-generators'
        ref: 1.2.0
        repository: 'nix-community/nixos-generators'
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: tangerinixos
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: $GITHUB_WORKSPACE/.github/workflows/test_build.sh
      shell: bash
